import { Router } from 'express';
import * as books from '../controllers/bookController.js';
import * as extras from '../controllers/catalogExtrasController.js';
import { protect, staffOnly, optionalProtect } from '../middleware/auth.js';
import { pdfUpload } from '../middleware/uploadPdf.js';
import { coverUpload } from '../middleware/uploadCover.js';

const r = Router();
r.get('/', optionalProtect, books.listBooks);
r.get('/genres', books.listGenres);
r.get('/categories', extras.listCategories);
r.get('/upcoming', books.listUpcoming);
r.get('/visitor', extras.listVisitorBooks);
r.get('/free', optionalProtect, extras.listFreeBooks);
r.get('/recent', protect, books.recentBooks);
r.get('/wishlist', protect, extras.listWishlist);
r.get('/wishlist/ids', protect, extras.wishlistIds);
r.get('/cart', protect, extras.listCart);
r.get('/cart/ids', protect, extras.cartIds);
r.delete('/cart', protect, extras.clearCart);
r.get('/barcode/:barcode', protect, staffOnly, books.lookupBarcode);
r.get('/lookup/:barcode', protect, staffOnly, books.lookupBarcode);
r.get('/:id/related', optionalProtect, extras.relatedBooks);
r.get('/:id/reviews', extras.listReviews);
r.post('/:id/reviews', protect, extras.upsertReview);
r.delete('/:id/reviews/:reviewId', protect, extras.deleteReview);
r.post('/:id/wishlist', protect, extras.addWishlist);
r.delete('/:id/wishlist', protect, extras.removeWishlist);
r.post('/:id/cart', protect, extras.addCart);
r.delete('/:id/cart', protect, extras.removeCart);
r.get('/:id/progress', protect, extras.getProgress);
r.put('/:id/progress', protect, extras.saveProgress);
r.get('/:id/read', optionalProtect, extras.readBook);
r.get('/:id/pdf', protect, extras.downloadPdf);
r.post('/:id/pdf', protect, staffOnly, pdfUpload.single('pdf'), books.uploadBookPdf);
r.post('/:id/cover', protect, staffOnly, coverUpload.single('cover'), books.uploadBookCover);
r.get('/:id', optionalProtect, books.getBook);
r.post('/', protect, staffOnly, books.createBook);
r.patch('/:id', protect, staffOnly, books.updateBook);
r.post('/:id/copies', protect, staffOnly, books.addCopies);
r.patch('/copies/:copyId', protect, staffOnly, books.updateCopy);
export default r;
