import { Book } from '../src/models/Book.js';
import { BookCopy } from '../src/models/BookCopy.js';
import { generateBarcode } from '../src/utils/ids.js';

const cover = (isbn) => `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;

export const CANONICAL_BOOKS = [
  {
    title: 'The Hobbit',
    authors: ['J. R. R. Tolkien'],
    isbn: '9780547928227',
    category: 'Fantasy',
    genres: ['Fantasy', 'Adventure', 'Classic'],
    summary: 'Bilbo Baggins joins a quest to reclaim a dwarf kingdom from the dragon Smaug.',
    publisher: 'Houghton Mifflin Harcourt',
    publicationYear: 1937,
    pages: 310,
    featured: true,
  },
  {
    title: 'Pride and Prejudice',
    authors: ['Jane Austen'],
    isbn: '9780141439518',
    category: 'Romance',
    genres: ['Romance', 'Classic', 'Fiction and Literature'],
    summary: 'Elizabeth Bennet navigates manners, marriage, and misunderstanding in Georgian England.',
    publisher: 'Penguin Classics',
    publicationYear: 1813,
    pages: 480,
  },
  {
    title: '1984',
    authors: ['George Orwell'],
    isbn: '9780451524935',
    category: 'Science Fiction',
    genres: ['Science Fiction', 'Classic', 'Politics'],
    summary: 'Winston Smith struggles against a totalitarian regime that rewrites truth itself.',
    publisher: 'Signet Classics',
    publicationYear: 1949,
    pages: 328,
    featured: true,
  },
  {
    title: 'Frankenstein',
    authors: ['Mary Shelley'],
    isbn: '9780486282114',
    category: 'Horror',
    genres: ['Horror', 'Gothic', 'Science Fiction'],
    summary: 'Victor Frankenstein creates life and is haunted by the consequences.',
    publisher: 'Dover Publications',
    publicationYear: 1818,
    pages: 166,
  },
  {
    title: 'The Adventures of Sherlock Holmes',
    authors: ['Arthur Conan Doyle'],
    isbn: '9780140439076',
    category: 'Mystery',
    genres: ['Mystery/Detective', 'Classic', 'Short Story Collection'],
    summary: 'Twelve cases featuring Sherlock Holmes and Dr. Watson in Victorian London.',
    publisher: 'Penguin Classics',
    publicationYear: 1892,
    pages: 334,
  },
  {
    title: 'Moby-Dick',
    authors: ['Herman Melville'],
    isbn: '9780142437247',
    category: 'Adventure',
    genres: ['Adventure', 'Nautical', 'Classic'],
    summary: 'Captain Ahab hunts the white whale across the world’s oceans.',
    publisher: 'Penguin Classics',
    publicationYear: 1851,
    pages: 720,
  },
  {
    title: 'The Odyssey',
    authors: ['Homer'],
    isbn: '9780140268867',
    category: 'Classic',
    genres: ['Classic', 'Myth', 'Poetry'],
    summary: 'Odysseus journeys home after the Trojan War through gods, monsters, and memory.',
    publisher: 'Penguin Classics',
    publicationYear: 1997,
    pages: 541,
  },
  {
    title: 'A Brief History of Time',
    authors: ['Stephen Hawking'],
    isbn: '9780553380163',
    category: 'Science',
    genres: ['Science', 'Non-fiction', 'Physics'],
    summary: 'A public introduction to cosmology, black holes, and the nature of time.',
    publisher: 'Bantam',
    publicationYear: 1988,
    pages: 212,
  },
  {
    title: 'The Art of War',
    authors: ['Sun Tzu'],
    isbn: '9781599869773',
    category: 'Philosophy',
    genres: ['Philosophy', 'War', 'Instructional'],
    summary: 'Classical Chinese treatise on strategy, leadership, and conflict.',
    publisher: 'Filiquarian',
    publicationYear: 2007,
    pages: 82,
  },
  {
    title: 'Treasure Island',
    authors: ['Robert Louis Stevenson'],
    isbn: '9780141321004',
    category: 'Adventure',
    genres: ['Adventure', 'Pirate Tales', 'Young Readers'],
    summary: 'Jim Hawkins sails in search of buried treasure and meets Long John Silver.',
    publisher: 'Puffin Classics',
    publicationYear: 1883,
    pages: 304,
  },
  {
    title: 'Dracula',
    authors: ['Bram Stoker'],
    isbn: '9780141439846',
    category: 'Horror',
    genres: ['Horror', 'Gothic', 'Classic'],
    summary: 'Count Dracula travels from Transylvania to England in this epistolary vampire novel.',
    publisher: 'Penguin Classics',
    publicationYear: 1897,
    pages: 454,
  },
  {
    title: 'Little Women',
    authors: ['Louisa May Alcott'],
    isbn: '9780147514011',
    category: 'Classic',
    genres: ['Classic', 'Young Readers', "Women's Studies"],
    summary: 'The March sisters grow up together through love, work, and wartime absence.',
    publisher: 'Puffin',
    publicationYear: 1868,
    pages: 449,
  },
  {
    title: 'The Republic',
    authors: ['Plato'],
    isbn: '9780140455113',
    category: 'Philosophy',
    genres: ['Philosophy', 'Politics', 'Classic'],
    summary: 'Socratic dialogues on justice, education, and the ideal city.',
    publisher: 'Penguin Classics',
    publicationYear: 2007,
    pages: 416,
  },
  {
    title: 'On the Origin of Species',
    authors: ['Charles Darwin'],
    isbn: '9780451529060',
    category: 'Science',
    genres: ['Science', 'Nature', 'Non-fiction'],
    summary: 'Darwin’s argument for evolution by natural selection.',
    publisher: 'Signet',
    publicationYear: 1859,
    pages: 576,
  },
  {
    title: 'The Picture of Dorian Gray',
    authors: ['Oscar Wilde'],
    isbn: '9780141439570',
    category: 'Classic',
    genres: ['Classic', 'Gothic', 'Fiction and Literature'],
    summary: 'A beautiful young man remains youthful while his portrait bears his sins.',
    publisher: 'Penguin Classics',
    publicationYear: 1890,
    pages: 304,
  },
  {
    title: 'Jane Eyre',
    authors: ['Charlotte Brontë'],
    isbn: '9780141441146',
    category: 'Romance',
    genres: ['Romance', 'Gothic', 'Classic'],
    summary: 'An orphaned governess seeks independence and love at Thornfield Hall.',
    publisher: 'Penguin Classics',
    publicationYear: 1847,
    pages: 532,
  },
  {
    title: 'The War of the Worlds',
    authors: ['H. G. Wells'],
    isbn: '9780141441030',
    category: 'Science Fiction',
    genres: ['Science Fiction', 'Classic', 'Thriller'],
    summary: 'Martians invade England in this foundational science-fiction novel.',
    publisher: 'Penguin Classics',
    publicationYear: 1898,
    pages: 240,
  },
  {
    title: 'The Count of Monte Cristo',
    authors: ['Alexandre Dumas'],
    isbn: '9780140449266',
    category: 'Adventure',
    genres: ['Adventure', 'Classic', 'Thriller'],
    summary: 'Edmond Dantès escapes prison and pursues an elaborate revenge.',
    publisher: 'Penguin Classics',
    publicationYear: 1844,
    pages: 1276,
  },
  {
    title: 'Leaves of Grass',
    authors: ['Walt Whitman'],
    isbn: '9780140421996',
    category: 'Poetry',
    genres: ['Poetry', 'Classic', 'Essays'],
    summary: 'Whitman’s evolving collection celebrating the self, democracy, and the body.',
    publisher: 'Penguin Classics',
    publicationYear: 1855,
    pages: 145,
  },
  {
    title: 'Narrative of the Life of Frederick Douglass',
    authors: ['Frederick Douglass'],
    isbn: '9780486284996',
    category: 'Biography',
    genres: ['Biography', 'African-American Studies', 'History'],
    summary: 'Douglass recounts his life in slavery and his path to freedom and literacy.',
    publisher: 'Dover',
    publicationYear: 1845,
    pages: 76,
    featured: true,
  },
  {
    title: 'The Adventures of Tom Sawyer',
    authors: ['Mark Twain'],
    isbn: '9780143039563',
    category: 'Adventure',
    genres: ['Adventure', 'Young Readers', 'Humor'],
    summary: 'Tom Sawyer’s Mississippi childhood of mischief, treasure, and moral growth.',
    publisher: 'Penguin Classics',
    publicationYear: 1876,
    pages: 244,
  },
  {
    title: 'The Time Machine',
    authors: ['H. G. Wells'],
    isbn: '9780141439976',
    category: 'Science Fiction',
    genres: ['Science Fiction', 'Classic', 'Adventure'],
    summary: 'A Victorian inventor travels to the far future and meets the Eloi and Morlocks.',
    publisher: 'Penguin Classics',
    publicationYear: 1895,
    pages: 104,
    isUpcoming: false,
  },
  {
    title: "Alice's Adventures in Wonderland",
    authors: ['Lewis Carroll'],
    isbn: '9780141439761',
    category: 'Fantasy',
    genres: ['Fantasy', 'Young Readers', 'Classic'],
    summary: 'Alice falls down a rabbit hole into a world of logic games and nonsense.',
    publisher: 'Penguin Classics',
    publicationYear: 1865,
    pages: 192,
  },
  {
    title: 'The Haunting of Hill House',
    authors: ['Shirley Jackson'],
    isbn: '9780143039983',
    category: 'Horror',
    genres: ['Horror', 'Gothic', 'Ghost Stories'],
    summary: 'Four seekers spend a summer in a house that may be genuinely haunted.',
    publisher: 'Penguin Classics',
    publicationYear: 1959,
    pages: 182,
  },
].map((b) => ({
  language: 'English',
  coverImage: cover(b.isbn),
  isbn10: '',
  subtitle: '',
  tags: b.genres,
  shelfLocation: `${b.category.slice(0, 2).toUpperCase()}-CAN`,
  ...b,
}));

export async function upsertCanonicalBooks() {
  const results = [];
  for (const book of CANONICAL_BOOKS) {
    const saved = await Book.findOneAndUpdate(
      { isbn: book.isbn },
      { $set: book },
      { upsert: true, new: true, setDefaultsOnInsert: true },
    );
    const copies = await BookCopy.countDocuments({ bookId: saved._id });
    if (copies === 0) {
      const last = await BookCopy.findOne().sort({ barcode: -1 }).select('barcode').lean();
      const n = Number(String(last?.barcode || '100000').replace(/\D/g, '')) || 100000;
      const docs = [1, 2, 3].map((i) => {
        const barcode = generateBarcode(n + i);
        return {
          bookId: saved._id,
          barcode,
          accessionNumber: barcode,
          condition: 'GOOD',
          status: 'AVAILABLE',
          shelfLocation: saved.shelfLocation,
        };
      });
      await BookCopy.insertMany(docs);
      saved.totalCopies = 3;
      saved.availableCopies = 3;
      await saved.save();
    }
    results.push(saved);
  }
  return results;
}
